services:
  app1:
    build: ./app1
    image: node-app1
    hostname: app1
    # start app1_db before app1
    # what if app1_db is not ready yet?
    # depends_on:
    #  - app1_db
    # wait for app1_db to be ready before starting app1
    depends_on:
      app1_db:
        condition: service_healthy
    # if you want to expose app1 directly (not via reverse proxy)
    # ports:
    #  - "127.0.0.1:3000:3000"
    # syntax for environment variables as a list
    labels:
      - "traefik.enable=true" # active l'exposition via Traefik
      - "traefik.http.routers.app1.rule=PathPrefix(`/app1`)"  # règle de routage
      - "traefik.http.routers.app1.middlewares=app1-stripprefix"  # applique le middleware
      - "traefik.http.middlewares.app1-stripprefix.stripprefix.prefixes=/app1"  # retire /app1 du chemin
      - "traefik.http.services.app1.loadbalancer.server.port=3000"  # port interne exposé
      - "traefik.docker.network=public_net" # app1 on public_net
    environment:
      - DB_HOST=app1_db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=app1db
    networks:
      - app1_net
      - public_net
  
  app1_db:
    hostname: app1_db
    image: mysql:8.4
    # syntax for environment variables as a mapping (dictionary / yaml object)
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app1db
    healthcheck:
      # inside the container, mysqladmin is available
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - app1_db_data:/var/lib/mysql
    networks:
      app1_net:
        aliases:
          - app1_db
          - mysql.db

  app2:
    image: traefik/whoami
    hostname: app2
    labels:
      - "traefik.enable=true" # active l'exposition via Traefik
      - "traefik.http.routers.app2.rule=PathPrefix(`/app2`)"  # règle de routage
      - "traefik.http.services.app2.loadbalancer.server.port=80"  # port interne exposé
      - "traefik.docker.network=public_net" # app2 on public_net
    # if you want to expose app2 directly (not via reverse proxy)
    # ports:
    #   - "127.0.0.1:3001:80"
    networks:
      - app2_net
      - public_net

  rproxy_nginx:
    profiles: [nginx]
    image: nginx:latest
    hostname: rproxy_nginx
    # add depends on for app1 and app2 
    # (otherwise nginx may fail to start if config references services that are not up yet)
    # /!\ we may need conditions here in more complex setups
    depends_on:
      - app1
      - app2
    ports:
      - "8080:80"
      # - "4443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - public_net

  rproxy_traefik:
    profiles: [traefik]
    image: traefik:2.9.10
    hostname: rproxy_traefik
    ports:
      - "8080:80"
      - "8443:443"
      - "8888:8080" # Traefik dashboard
    command:
      - "--api.insecure=true" # enable Traefik dashboard
      - "--providers.docker=true" # enable Docker provider (traefik reads labels from containers)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # allow Traefik to listen to Docker events
    networks:
      - public_net
    

volumes:
  app1_db_data:
    name: app1_db_data
    external: false

networks:
  app1_net:
    external: false
    name: app1_net
    driver: bridge

  app2_net:
    external: false
    name: app2_net
    driver: bridge

  public_net:
    external: false
    name: public_net
    driver: bridge