# We can split our stack compose file into multiple files
# Here we have a compose file for app1 only
# include:
#   - ./app1/compose.yml
services:
  app1:
    build: ./app1
    image: node-app1
    hostname: app1
    # start app1_db before app1
    # what if app1_db is not ready yet?
    # depends_on:
    #  - app1_db
    # wait for app1_db to be ready before starting app1
    depends_on:
      app1_db:
        condition: service_healthy
        restart: true # if app1_db fails or restarts, restart app1 also
    
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
        
      
    # labels for traefik reverse proxy
    labels:
      - "traefik.enable=true" # active l'exposition via Traefik
      - "traefik.http.routers.app1.rule=PathPrefix(`/app1`)"  # règle de routage
      - "traefik.http.routers.app1.middlewares=app1-stripprefix"  # applique le middleware
      - "traefik.http.middlewares.app1-stripprefix.stripprefix.prefixes=/app1"  # retire /app1 du chemin
      - "traefik.http.services.app1.loadbalancer.server.port=3000"  # port interne exposé
      - "traefik.docker.network=public_net" # app1 on public_net  

    # syntax for environment variables as a list
    # environment:
    #   - DB_HOST=app1_db
    #   - DB_USER=root
    #   - DB_PASSWORD=root
    #   - DB_NAME=app1db
    # environment variables from .env file
    env_file:
      - .env

    # if you want to expose app1 directly (not via reverse proxy)
    # ports:
    #  - "127.0.0.1:3000:3000"

    networks:
      - app1_net
      - public_net
    
    # if no logging specified, default json-file driver is used
    # if json-file driver is used, we need to limit log size to avoid filling disk
    # (like a log rotation)
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
  
  app1_db:
    hostname: app1_db
    image: mysql:8.4
    restart: unless-stopped
    # syntax for environment variables as a mapping (dictionary / yaml object)
    # use environment variables from .env file (load .env)
    env_file: 
      - .env
    # environment:
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    healthcheck:
      # inside the container, mysqladmin is available
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - app1_db_data:/var/lib/mysql
    networks:
      app1_net:
        aliases:
          - app1_db
          - mysql.db

  app2:
    image: traefik/whoami
    hostname: app2
    restart: unless-stopped
    labels:
      - "traefik.enable=true" # active l'exposition via Traefik
      - "traefik.http.routers.app2.rule=PathPrefix(`/app2`)"  # règle de routage
      - "traefik.http.services.app2.loadbalancer.server.port=80"  # port interne exposé
      - "traefik.docker.network=public_net" # app2 on public_net
    # if you want to expose app2 directly (not via reverse proxy)
    # ports:
    #   - "127.0.0.1:3001:80"
    networks:
      - app2_net
      - public_net

  rproxy_nginx:
    profiles: [nginx]
    image: nginx:latest
    hostname: rproxy_nginx
    restart: unless-stopped
    # add depends on for app1 and app2 
    # (otherwise nginx may fail to start if config references services that are not up yet)
    # /!\ we may need conditions here in more complex setups
    depends_on:
      - app1
      - app2
    ports:
      - "8080:80"
      # - "4443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - public_net

  rproxy_traefik:
    profiles: [traefik]
    image: traefik:2.9.10
    hostname: rproxy_traefik
    restart: unless-stopped
    # dont need privileged mode (no docker in docker, just need docker socket access)
    privileged: false
    ports:
      - "8080:80"
      - "8443:443"
      - "8888:8080" # Traefik dashboard
    # Traefik has an entrypoint config in his dockerfile, we add command to override / extend it
    command:
      - "--api.insecure=true" # enable Traefik dashboard
      - "--providers.docker=true" # enable Docker provider (traefik reads labels from containers)
    # allow Traefik to listen to Docker events
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # allow Traefik to listen to Docker events
    networks:
      - public_net
    

volumes:
  app1_db_data:
    name: app1_db_data
    external: false

networks:
  app1_net:
    external: false
    name: app1_net
    driver: bridge

  app2_net:
    external: false
    name: app2_net
    driver: bridge

  public_net:
    external: false
    name: public_net
    driver: bridge